# .github/workflows/build-and-release.yml

name: AutoHotkey Build and Release

# 定义触发工作流的事件
on:
  release:
    types: [published] # 当有新的 GitHub Release 被“发布”时触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build (With Icon)
        uses: benmusson/ahk2exe-action@v1
        with:
          in: .\Main.ahk
          out: .\Main.exe
          icon: .\UI_Main_Icon.ico
          target: x64
          ahk-tag: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
