# .github/workflows/build-and-release.yml

name: AutoHotkey Build and Release

# 定义触发工作流的事件
on:
  release:
    types: [published] # 当有新的 GitHub Release 被“发布”时触发

jobs:
  build_and_attach_release:
    runs-on: windows-latest # AutoHotkey 脚本在 Windows 环境下运行和编译

    steps:
      - name: Checkout repository # 步骤1: 拉取仓库代码
        uses: actions/checkout@v4

      - name: Compile AutoHotkey Script (v2) # 步骤2: 编译 AutoHotkey 脚本
        uses: lukelee/autohotkey-compiler-action@v1.0.0
        with:
          script: main.ahk # <-- 替换为您的主脚本文件名，例如：'main.ahk'
          output: Main.exe         # <-- 定义编译后可执行文件的名称，例如：'MyAwesomeApp.exe'
          arch: x64                  # 编译目标架构：x64 或 x86
          version: v2                # 指定 AutoHotkey 版本：v1 或 v2 (根据您的项目选择)

      - name: Upload Release Asset # 步骤3: 将编译好的 .exe 文件作为 Release Asset 上传
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的 token
        with:
          upload_url: ${{ github.event.release.upload_url }} # 上传到当前 Release 的 URL
          asset_path: ./Main.exe                     # <-- 替换为编译后文件的路径，与 output 名称一致
          asset_name: Main.exe                       # <-- 替换为 Release Asset 的名称
          asset_content_type: application/octet-stream  # 文件类型